name: Commit changes to Alarm.ts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  commit-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Commit changes to Alarm.ts
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        cp src/main.ts src/Alarm.ts
        git add src/Alarm.ts
        git commit -m 'Commit changes from main.ts to Alarm.ts'
        git pull --rebase origin main
        git push origin HEAD:main

    - name: Resolve merge conflicts
      uses: stefanzweifel/git-auto-commit-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        conflict-resolution-strategy: 'ours'
