name: Fetch and Upload Leds.ts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Checkout AlarmLeds repository
      uses: actions/checkout@v2
      with:
        repository: PinguinLars/AlarmLeds

    - name: Create Directory if it does not exist
      run: |
        mkdir -p .microbit/

    - name: Copy main.ts to Leds.ts
      run: |
        cp main.ts .microbit/Leds.ts

    - name: Commit and push changes
      run: |
        git config --global user.name 'PinguinLarsAlt'
        git config --global user.email 'PinguinLars1105@gmail.com'
        git add .microbit/Leds.ts
        git commit -m 'Update Leds.ts with latest main.ts from AlarmLeds'
        git push
