name: Cross repo sync's

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  Sync-Leds:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Checkout AlarmLeds repository
      uses: actions/checkout@v4
      with:
        repository: PinguinLars/AlarmLeds
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Create Directory if it does not exist
      run: |
        mkdir -p .microbit/

    - name: Copy main.ts to Leds.ts
      run: |
        cp main.ts .microbit/Leds.ts

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'PinguinLarsAlt'
        git config --global user.email 'PinguinLars1105@gmail.com'
        git add .microbit/Leds.ts
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Update Leds.ts with latest main.ts from AlarmLeds'
          git push https://github.com/PinguinLars/Anti-Boskap.git
        else
          echo "No changes to commit"
        fi
      
  Sync-Alarm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Checkout AlarmLeds repository
      uses: actions/checkout@v4
      with:
        repository: PinguinLars/MicroAlarmSound
        token: ${{ secrets.ACTIONS_PAT }}

    - name: Create Directory if it does not exist
      run: |
        mkdir -p .microbit/

    - name: Copy main.ts to Alarm.ts
      run: |
        cp main.ts .microbit/Alarm.ts

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'PinguinLarsAlt'
        git config --global user.email 'PinguinLars1105@gmail.com'
        git add .microbit/Alarm.ts
        if ! git diff-index --quiet HEAD; then
          git commit -m 'Update Alarm.ts with latest main.ts from MicroAlarmSound'
          git push https://github.com/PinguinLars/Anti-Boskap.git
        else
          echo "No changes to commit"
        fi
